### ISSUE TITLE
Broken for   me

### ISSUE THREAD

**Issue by amiind** [Leastrio/discord-welcome#2]
The code is ot working for me or I am dumb 
![image](https://user-images.githubusercontent.com/67783001/102702305-5d674800-4287-11eb-86a7-f405d3c40753.png)

**Comment by Leastrio** [comment]
Any errors in console?

**Comment by amiind** [comment]
Problem got fixed :) thank you for making this nice piece of work

Anyone who is facing similar issue , Make sure  you properly change the file locations and path
