### ISSUE TITLE
Cannot identify image

### ISSUE THREAD

**Issue by sagarvlog** [Leastrio/discord-welcome#3]
UserWarning: image file could not be identified because WEBP support not installed
raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'profile.jpg'

**Comment by Leastrio** [comment]
Not able to reproduce, make sure you dont have Pillow downloaded instead of PIL

**Comment by Leastrio** [comment]
Are you using Anaconda?
